/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreCallRouteImport } from './routes/pre-call'
import { Route as BookACallRouteImport } from './routes/book-a-call'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCalendlyDiagRouteImport } from './routes/api/public/calendly-diag'

const PreCallRoute = PreCallRouteImport.update({
  id: '/pre-call',
  path: '/pre-call',
  getParentRoute: () => rootRouteImport,
} as any)
const BookACallRoute = BookACallRouteImport.update({
  id: '/book-a-call',
  path: '/book-a-call',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendlyDiagRoute = ApiPublicCalendlyDiagRouteImport.update({
  id: '/api/public/calendly-diag',
  path: '/api/public/calendly-diag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-a-call': typeof BookACallRoute
  '/pre-call': typeof PreCallRoute
  '/api/public/calendly-diag': typeof ApiPublicCalendlyDiagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-a-call': typeof BookACallRoute
  '/pre-call': typeof PreCallRoute
  '/api/public/calendly-diag': typeof ApiPublicCalendlyDiagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-a-call': typeof BookACallRoute
  '/pre-call': typeof PreCallRoute
  '/api/public/calendly-diag': typeof ApiPublicCalendlyDiagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book-a-call' | '/pre-call' | '/api/public/calendly-diag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book-a-call' | '/pre-call' | '/api/public/calendly-diag'
  id:
    | '__root__'
    | '/'
    | '/book-a-call'
    | '/pre-call'
    | '/api/public/calendly-diag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookACallRoute: typeof BookACallRoute
  PreCallRoute: typeof PreCallRoute
  ApiPublicCalendlyDiagRoute: typeof ApiPublicCalendlyDiagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pre-call': {
      id: '/pre-call'
      path: '/pre-call'
      fullPath: '/pre-call'
      preLoaderRoute: typeof PreCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-call': {
      id: '/book-a-call'
      path: '/book-a-call'
      fullPath: '/book-a-call'
      preLoaderRoute: typeof BookACallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendly-diag': {
      id: '/api/public/calendly-diag'
      path: '/api/public/calendly-diag'
      fullPath: '/api/public/calendly-diag'
      preLoaderRoute: typeof ApiPublicCalendlyDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookACallRoute: BookACallRoute,
  PreCallRoute: PreCallRoute,
  ApiPublicCalendlyDiagRoute: ApiPublicCalendlyDiagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
